services:
  app:
    build: .
    environment:
      - NODE_ENV=development
    command: make dev
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app